### ISSUE TITLE
Getting Duplicate symbol error

### ISSUE THREAD

**Issue by nickqlx** [Yubico/yubikit-swift#3]
I am encountering a duplicate symbol error while running my primary project, even though I have added package dependency in my custom library and built it without errors. The error message specifies that there is a duplicate symbol. Can you assist me in resolving this issue?

duplicate symbol '_$s7YubiKit11OATHSessionC11setPasswordyySSYaKF' in:
    /Users/macbook/Library/Developer/Xcode/DerivedData/U360-dvjmektnilmeqnctxzynwuvfdsco/Build/Products/Release-iphoneos/libU360.a[304](YubiKiu.o)
    /Users/macbook/Library/Developer/Xcode/DerivedData/U360-dvjmektnilmeqnctxzynwuvfdsco/Build/Products/Release-iphoneos/libU360.a[301](YubiKit.o)
ld: 797 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jensutbult** [comment]
Do you think you can distill this to a small sample project and share it with me?

**Comment by nickqlx** [comment]
I have resolved the issue. It turned out to be a problem with my code. Thank you for getting back to me.
