### ISSUE TITLE
Release status and roadmap?

### ISSUE THREAD

**Issue by natevw** [Yubico/yubikit-swift#6]
The README currently says:

https://github.com/Yubico/yubikit-swift/blob/4666a2b7989081c1563204cee6f3ba16305e7d5f/README.md?plain=1#L5

Would you be able to elaborate on this guidance? If a new project were getting underway and was willing to accept some API instability and/or helping test some potentially-unfinished corners, would we still be strongly discouraged to deploy something built on this codebase?

**Comment by jensutbult** [comment]
As long as you only need the functionality currently implemented and will accept breaking changes in the future it should be ok.
